version: '3.8'

services:
  app:
    image: geoapi-app:prod
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geoapi-app-prod
    restart: unless-stopped
    environment:
      - APP_ENV=production
      - APP_DEBUG=0
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
      - APP_KEY=your-production-app-key
    # Untuk production, sebaiknya hanya mount storage agar image lebih aman dan stabil
    volumes:
      - ./storage:/var/www/storage
    networks:
      - geoapi

  nginx:
    image: nginx:1.25-alpine
    container_name: geoapi-nginx-prod
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - geoapi

  traefik:
    image: traefik:v2.11
    container_name: geoapi-traefik
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=admin@yourdomain.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/letsencrypt:/letsencrypt
    networks:
      - geoapi

networks:
  geoapi:
    driver: bridge
